#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export ISPH_LIBS="$HOME/git/zsph"
export PATH="$HOME/git/zsph/bin:$PATH"
export GIT_SSL_NO_VERIFY=1

export PATH="$HOME/.bin:$PATH"
export PATH="/usr/lib64/openmpi/bin/:$PATH"

export MAVEN_OPTS=-Xmx1024m

export LESS=" -R"
export LESSOPEN="| src-hilite-lesspipe.sh %s"
