#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Enable Z
source "$HOME/.dotz/z/z.sh"

# Customize to your needs...
setopt extended_glob

# Enable fzf
distro=$( grep -zohP '(?<=^NAME=).*' /etc/os-release | sed 's/[^a-zA-Z0-9]//g')
case $distro in
    "ArchLinux")
        fzf_files=(/usr/share/fzf/completion.zsh /usr/share/fzf/key-bindings.zsh)
        ;;
    "Fedora")
        fzf_files=(/usr/share/zsh/site-functions/fzf /usr/share/fzf/shell/key-bindings.zsh)
        ;;
    *)
        echo kek
        ;;
esac

for fzf_file in $fzf_files; do
    [[ -f $fzf_file ]] && source $fzf_file
done

# Load custom shell functions
if [[ -d "$HOME/.zsh" ]]; then
	for f in $HOME/.zsh/*.sh(N); source "$f";
fi;

# Additional key bindings
bindkey '^[[1;5D' backward-word                       # ctrl+left
bindkey '^[[1;5C' forward-word                        # ctrl+right
bindkey '^R'      history-incremental-search-backward # ctrl+r
bindkey '^[.'     insert-last-word                    # alt+.
